src/main/java/com/assoc/jad/bean/FamilyBean.java
package com.assoc.jad.bean;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import javax.faces.model.SelectItem;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.ocpsoft.rewrite.el.ELBeanName;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.assoc.jad.hbm.email.EmailController;
import com.assoc.jad.hbm.shoplist.Shoplist;
import com.assoc.jad.hbm.shoplist.ShoplistController;
import com.assoc.jad.hbm.stores.StoreController;
import com.assoc.jad.tools.ShopListStatic;

@Scope(value = "session")
@Component(value = "familyBean")
@ELBeanName(value = "familyBean")
public class FamilyBean implements Serializable {
	private static final long serialVersionUID = 1L;

	@Autowired
	ShoplistController shoplistController;
	@Autowired
	StoreController storeController;
	@Autowired
	EmailController emailController;

	private static final String REDIRECTED = "redirected";
	private Shoplist	shoplist 		= new Shoplist();
	private String 	infomsg="";
	private String 	familyKey;
	private String	emailList;
	private String	itemList;
	private String	navigator;
	private String email;
	private String storeName;
	private List<SelectItem> familyList  = new ArrayList<SelectItem>();
	private String familyId;

	public FamilyBean() {
	}
	private void addFamilyItem(String name,Long id) {
		SelectItem item = new SelectItem();
		item.setLabel(name+";"+email);
		item.setValue(id.toString());
		familyList.add(item);		
	}
	private String getHTMLParam(String name) {
		FacesContext context = FacesContext.getCurrentInstance();
		ExternalContext external = context.getExternalContext();
		HttpServletRequest request = (HttpServletRequest) external.getRequest();
		return request.getParameter(name);
	}
	private void resetCookie(String name) {
		HttpServletRequest req   =  (HttpServletRequest)FacesContext.getCurrentInstance().getExternalContext().getRequest();
		HttpServletResponse resp =  (HttpServletResponse)FacesContext.getCurrentInstance().getExternalContext().getResponse();
		Cookie[] cookies = req.getCookies();
		if (cookies != null) 
			for (int i=0;i<cookies.length;i++) {
				if (name.equals(cookies[i].getName())) {
					cookies[i].setValue("");
		            cookies[i].setMaxAge(0);
		            resp.addCookie(cookies[i]);
					break;
				}
			}
	}
	private void getEmailFromCookie() {
		String wrkEmail = "";
		HttpServletRequest req   =  (HttpServletRequest)FacesContext.getCurrentInstance().getExternalContext().getRequest();
		Cookie[] cookies = req.getCookies();
		if (cookies != null) 
			for (int i=0;i<cookies.length;i++) {
				if ("email".equals(cookies[i].getName())) {
					wrkEmail = cookies[i].getValue();
					break;
				}
			}
		if (wrkEmail.length() == 0 || wrkEmail.equals(email)) {
			wrkEmail = getHTMLParam("email");
			if (wrkEmail == null) wrkEmail = getHTMLParam("parm"); //iphone interprets 'email' to start mail app
			if (wrkEmail != null && (wrkEmail.length() == 0 || wrkEmail.equals(email))) return;
		}
		if (wrkEmail != null) email = wrkEmail;
		getFamilyUsingEmail();
	}
	private void setEmailFromCookie() {
		HttpServletResponse resp =  (HttpServletResponse)FacesContext.getCurrentInstance().getExternalContext().getResponse();
		Cookie cookie = new Cookie("email",email);
		try {  //android fails when setting a cookie
	    resp.addCookie( cookie );
		}catch (Exception e) {}
	}
	private boolean isFamilyReady() {
		infomsg="";
		if (shoplist.getId() <= 0 || shoplist.getListname() == null) {
			infomsg = "needs to have a shoplist record. Click 'select a shoplist' from menu";
			//savedNavigation = getRedirect();
			return false;
		}
		getFamilyUsingId(); //resync shoplist object with possible changes to 'familyid'
		return true;
	}
	private boolean getMasterListBean() {
		ExternalContext external = FacesContext.getCurrentInstance().getExternalContext();
		HttpServletRequest req  = (HttpServletRequest) external.getRequest();
		MasterListBean masterListBean = (MasterListBean)req.getSession().getAttribute("masterListBean");
		if (masterListBean == null) {
			masterListBean = new MasterListBean();
			req.getSession().setAttribute("masterListBean",masterListBean);
		}
		storeController.initStore(shoplist);
		storeController.loadAllStores();
		masterListBean.setStoreShopList(storeController.getStoreShopList());
		masterListBean.setShoplist(shoplist);
		return true;
	}
	private void getFamilyUsingEmail() {
		if (email == null || email.length() == 0) return;
		if (shoplist != null && 
			(familyId != null && familyId.length() > 0) &&
			email.equals(shoplist.getEmail()) && shoplist.getId() == (new Long(familyId)).longValue()) return;
		
		List<Shoplist> wrkList = shoplistController.getfamilyWithEmail(email);
		if (wrkList == null) {
			ShopListStatic.redirect(ShopListStatic.NEWSHOPPINGLIST);
			return;
		}
		
		getMasterListBean();
		if (wrkList.size() == 1) {
			shoplist = (Shoplist)wrkList.get(0);
			familyId = new Long(shoplist.getId()).toString();
			ShopListStatic.redirect(ShopListStatic.STORELIST);
			return;
		}
		familyList  = new ArrayList<SelectItem>();
		for (int i=0;i<wrkList.size();i++) {
			shoplist = (Shoplist)wrkList.get(i);
			addFamilyItem(shoplist.getListname(),shoplist.getId());
		}
		familyId = "";
		navigator = FamilyBean.REDIRECTED;
		ShopListStatic.redirect(ShopListStatic.SELECTFAMILY2);
		return;
	}
	private void getFamilyUsingId() {
		if (familyId == null || familyId.length() == 0) return;
		if (shoplist.getId() == (new Long(familyId)).longValue()) {
			ShopListStatic.redirect(ShopListStatic.STORELIST);
			return;
		}
		
		shoplist = shoplistController.getFamily(new Long(familyId));
		getMasterListBean();
		ShopListStatic.redirect(ShopListStatic.STORELIST);
	}
	private boolean addFamily() {
		shoplistController.createFamily();
		infomsg = shoplistController.getInfomsg();
		familyKey = shoplistController.getFamilyKey();
		shoplist = shoplistController.getFamily();
		return shoplistController.isSQLStatusOK();
	}
	private void resetInfomsg() {
		HttpServletRequest req  = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
		MasterListBean masterListBean = (MasterListBean)req.getSession().getAttribute("masterListBean");
		if (masterListBean != null) masterListBean.setInfomsg("");
		infomsg = "";
	}
	
	
	public void familyViaEmail(ActionEvent event) {
		if (REDIRECTED.equals(navigator)) return;
		navigator = "selectFamily";
		getFamilyUsingId();
	}
	public void newShoppingList(ActionEvent event) {
		shoplist.setEmail(email);
		addFamily();
	}
	public void additemList(ActionEvent event) {
		resetInfomsg();
		if (storeName == null || storeName.length() == 0 || 
			itemList == null || itemList.trim().length() == 0) return;
		
		String[] wrkArray = itemList.split("(:|\\s+|\\n|\\t|;|,)");
		List<String> list = Arrays.asList(wrkArray);;

		storeController.initStore(shoplist);
		storeController.loadAllStores();
		storeController.addList(storeName,list);
		infomsg = storeController.getInfomsg();
	}

	public void addFamily(ActionEvent event) {
			navigator = "addFamily";
			if (addFamily()) navigator = "addEmails";
	}
	public void addEmails(ActionEvent event) {
		navigator = "getShoplist";
		familyId = null;  //shoplist already verified familyid is not releveant
		if (!isFamilyReady()) return;
		
		emailController.initEmail(shoplist);
		emailController.addEmails(emailList);
		infomsg = emailController.getInfomsg();
		familyKey = emailController.getShoplistKey();
		shoplist = emailController.getShoplist();
		navigator = "addEmails";
		if (emailController.isSQLStatusOK()) navigator = "addShoppingList";
	}
	public String navigation() {
		return navigator;
	}
	/*
	 * getters and setters
	 */
	public Shoplist getShoplist() {
		return shoplist;
	}
	public void setFamily(Shoplist shoplist) {
		this.shoplist = shoplist;
	}
	public String getInfomsg() {
		return infomsg;
	}
	public void setInfomsg(String infomsg) {
		this.infomsg = infomsg;
	}
	public String getFamilyKey() {
		return ShopListStatic.undoSpecialChars(familyKey);
	}
	public void setFamilyKey(String familyKey) {
		this.familyKey = familyKey;
	}
	public void setEmail(String email) {
		setEmailFromCookie();
		this.email = email;
	}
	public String getEmail() {
		getEmailFromCookie();
		return email;
	}
	public String getEmail2() {
		return email;
	}
	public void setEmail2(String email) {
		this.email = email;
	}
	public String getEmailList() {
		return emailList;
	}
	public void setEmailList(String emailList) {
		this.emailList = emailList;
	}
	public List<SelectItem> getFamilyList() {
		if (email == null || email.length() == 0) return familyList;

		familyList = new ArrayList<SelectItem>();
		List<Shoplist> wrkList = shoplistController.getfamilyWithEmail(email);
		if (wrkList == null) {
			infomsg = "no shoplist for email="+email+" in DB";
			return familyList;
		}
		infomsg = shoplistController.getInfomsg();
		Shoplist wrkFamily = new Shoplist();
		for (int i=0;i<wrkList.size();i++) {
			wrkFamily = (Shoplist)wrkList.get(i);
			addFamilyItem(wrkFamily.getListname(),wrkFamily.getId());
		}
		return familyList;
	}
	public String getHtml() {
		if (navigator == null || navigator.length() == 0) navigator = "addFamily";
		return navigator;
	}
	public String getStoreName() {
		return storeName;
	}
	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}
	public String getFamilyId() {
		getFamilyUsingId();
		return familyId;
	}
	public void setFamilyId(String familyId) {
		this.familyId = familyId;
		getFamilyUsingId();
	}
	public void setResetFamily(String familyId) {
		resetCookie("email");
		email = "";
		this.familyId = null;
	}

src/main/java/com/assoc/jad/bean/ScratchPadBean.java
package com.assoc.jad.bean;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean
@SessionScoped
public class ScratchPadBean {
	private String saveSelectedList;

	public String getSaveSelectedList() {
		return saveSelectedList;
	}

	public void setSaveSelectedList(String saveSelectedList) {
		this.saveSelectedList = saveSelectedList;
	}
}

src/main/java/com/assoc/jad/hbm/family/FamilyController.java
package com.assoc.jad.hbm.family;

import java.sql.Timestamp;
import java.util.Date;
import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;

import com.assoc.jad.tools.ShopListStatic;

@Controller 
public class FamilyController {
	
	@Autowired
	FamilyService familyService;
	
	private Family	family;
	private String 	infomsg		="";
	private boolean SQLStatusOK = false;
	private String 	familyKey;
	
	public FamilyController(Family family) {
		this.family = family;
	}
	public FamilyController() {
		family = new Family();
	}
	private boolean familyExist() {
		SQLStatusOK=false;
		String Firstname = ShopListStatic.specialChars(family.getFirstname());


		List<Family> wrkList = familyService.findAllByFirstnameAndEmail(Firstname,family.getEmail());
		if (wrkList == null || wrkList.size() == 0) return false;
		
		infomsg = "and identical family already exist ";
		family = (Family)wrkList.get(0);   //TODO there might be more than one row.
		familyKey += family.getId();
		return true;
	}
	private Family familyViaId(Long id) {
		SQLStatusOK=false;
		infomsg = "";
		Optional<Family> wrkList = familyService.findById(id);
		if (!wrkList.isPresent()) {
			infomsg = "there are no family for id="+id;
			return null;
		}
		SQLStatusOK=true;
		return wrkList.get();
	}
	private List<Family> familyWithEmail(String email) {
		SQLStatusOK=false;
		infomsg = "";
		List<Family> wrkList = familyService.findAllByEmailIgnoreCase(email); 
		if (wrkList == null || wrkList.size() == 0) {
			infomsg = "there are no family tree for email="+email;
			return null;
		}
		SQLStatusOK=true;
		return wrkList;
	}
	private boolean insertFamily() {

		Date date = new Date();
		family.setCreatedate(new Timestamp(date.getTime()));
		family.setFirstname(ShopListStatic.specialChars(family.getFirstname()));

		familyService.insert(family);
		setInfomsg("successfully added a new family root: "+ShopListStatic.undoSpecialChars(familyKey));
		return true;
	}
	public void createFamily() {
		if (familyExist()) return;
		insertFamily();
	}
	public void updateEmails() {
		if (familyExist()) return;
		insertFamily();
		
	}
	/*
	 * getters and setters
	 */
	public String getInfomsg() {
		return infomsg;
	}
	public void setInfomsg(String infomsg) {
		this.infomsg = infomsg;
	}
	public Family getFamily() {
		return family;
	}
	public Family getFamily(Long id) {
		return familyViaId(id);
	}
	public void setFamily(Family family) {
		this.family = family;
	}
	public boolean isSQLStatusOK() {
		return SQLStatusOK;
	}
	public String getFamilyKey() {
		return familyKey;
	}
	public void setFamilyKey(String familyKey) {
		this.familyKey = familyKey;
	}
	public List<Family> getfamilyWithEmail(String email) {
		return familyWithEmail(email);
	}
}

src/main/java/com/assoc/jad/hbm/items/ItemController.java
package com.assoc.jad.hbm.items;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;

@Controller
public class ItemController {
	@Autowired
	ItemService itemService;

}

src/main/java/com/assoc/jad/hbm/photos/ItemPhotoController.java
package com.assoc.jad.hbm.photos;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;

@Controller
public class ItemPhotoController {
	@Autowired
	ItemPhotoService itemPhotoService;

}

src/main/java/com/assoc/jad/hbm/shoplist/ShoplistController.java
package com.assoc.jad.hbm.shoplist;

import java.sql.Timestamp;
import java.util.Date;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;

import com.assoc.jad.tools.ShopListStatic;

@Controller
public class ShoplistController {
	
	@Autowired
	private ShoplistService shoplistService;
	
	private Shoplist	shoplist;
	private String 	infomsg		="";
	private boolean SQLStatusOK = false;
	private String 	familyKey;
	
	public ShoplistController(Shoplist shoplist) {
		this.shoplist = shoplist;
	}
	public ShoplistController() {
		shoplist = new Shoplist();
	}
	private boolean shoplistExist() {
		String listname = ShopListStatic.specialChars(shoplist.getListname());

	   List<Shoplist> wrkList = shoplistService.findAllByListnameAndEmail(listname,shoplist.getEmail());
	   if (wrkList == null || wrkList.size() == 0) return false;
		
		if ( wrkList.size() > 1) infomsg = "and identical shoplist already exist ";
		shoplist = (Shoplist)wrkList.get(0);   //TODO there might be more than one row.
		familyKey += shoplist.getId();
		return true;
	}
	private Shoplist familyViaId(Long id) {
		SQLStatusOK=false;
		infomsg = "";
		
		List<Shoplist> wrkList = shoplistService.findAllById(id); 
		if (wrkList == null || wrkList.size() == 0) {
			infomsg = "there are no shoplist for id="+id;
			return null;
		}
		SQLStatusOK=true;
		return (Shoplist)wrkList.get(0);		
	}
	private List<Shoplist> familyWithEmail(String email) {
		SQLStatusOK=false;
		infomsg = "";
		List<Shoplist> wrkList = shoplistService.findAllByEmailIgnoreCase(email);
		if (wrkList == null || wrkList.size() == 0) {
			infomsg = "there are no shoplist tree for email="+email;
			return null;
		}
		SQLStatusOK=true;
		return wrkList;
	}
	private boolean insertShoplist() {
		Date date = new Date();
		shoplist.setCreatedate(new Timestamp(date.getTime()));
		shoplist.setListname(ShopListStatic.specialChars(shoplist.getListname()));

		shoplistService.insertShoplist(shoplist);
		familyKey = shoplist.getListname()+"."+shoplist.getId();
		setInfomsg("successfully added a new shoplist root: "+ShopListStatic.undoSpecialChars(familyKey));
		return true;
	}
	public void createFamily() {
		if (shoplistExist()) return;
		insertShoplist();
	}
	public void updateEmails() {
		if (shoplistExist()) return;
		insertShoplist();
		
	}
	/*
	 * getters and setters
	 */
	public String getInfomsg() {
		return infomsg;
	}
	public void setInfomsg(String infomsg) {
		this.infomsg = infomsg;
	}
	public Shoplist getFamily() {
		return shoplist;
	}
	public Shoplist getFamily(Long id) {
		return familyViaId(id);
	}
	public void setFamily(Shoplist shoplist) {
		this.shoplist = shoplist;
	}
	public boolean isSQLStatusOK() {
		return SQLStatusOK;
	}
	public String getFamilyKey() {
		return familyKey;
	}
	public void setFamilyKey(String familyKey) {
		this.familyKey = familyKey;
	}
	public List<Shoplist> getfamilyWithEmail(String email) {
		return familyWithEmail(email);
	}
}

src/main/webapp/addItems.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:h="http://java.sun.com/jsf/html" 
      xmlns:f="http://java.sun.com/jsf/core" 
	  xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:ui="http://java.sun.com/jsf/facelets" >
  <head>
    <link rel="stylesheet" href="includes/css/scrollNav.css" type="text/css"></link>
    <link rel="stylesheet" href="includes/css/style.css" type="text/css"></link>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script type="text/javascript" src="includes/js/shoplist.js"></script>
    <script type="text/javascript" src="includes/js/shoplistSupport.js"></script> 
    <script type="text/javascript" src="includes/js/ajax.js"></script> 
  </head>  
  <body onload="showNav('mainNavigation.xhtml');setMsg('','infoMessage');bldItemRow('addItems:admin')"> 
	<h:form id="addItems" styleClass="menuCol noborder">
	<div id="contentframe" class="center">
	  <h2>To add a new shopping Item to Stores</h2> 
		
	  <h4 id="infoMessage" style="infoMessage">#{masterListBean.infomsg}</h4>
	  <h:panelGrid columns="1" cellpadding="1" >
		<h:dataTable id="admin" value="" border="2" cellpadding="5" cellspacing="2">
			<h:column>Item name</h:column>
			<c:forEach items="#{masterListBean.allStoresNames.toArray()}" var="key">
				<h:column>#{key}</h:column> 
			</c:forEach>
		</h:dataTable>
	  </h:panelGrid>
	  <h:panelGroup>
	   	<h:commandButton value="Add item" onclick="tableAsJSON('addItems:admin','jsonarray')" actionListener="#{masterListBean.addItems}" style="margin-right:5px" />
	  </h:panelGroup>
	  <input type="hidden" value="addItems" id="formname" name="formname"/>
	  <input type="hidden" value="" id="jsonarray" name="jsonarray"/>
	</div>
	</h:form>
  </body> 
</html> 

src/main/webapp/addShoppingList.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:h="http://java.sun.com/jsf/html" 
      xmlns:f="http://java.sun.com/jsf/core" 
      xmlns:ui="http://java.sun.com/jsf/facelets" 
	  xmlns:t="http://myfaces.apache.org/tomahawk">
<head> 
    <link rel="stylesheet" href="includes/css/scrollNav.css" type="text/css"></link>
    <link rel="stylesheet" href="includes/css/style.css" type="text/css"></link>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script type="text/javascript" src="includes/js/shoplist.js"></script>
    <script type="text/javascript" src="includes/js/shoplistSupport.js"></script>
    <script type="text/javascript" src="includes/js/ajax.js"></script>
    <link href="includes/css/modal.css" type="text/css" rel="stylesheet" ></link>
</head>  
<body onload="showNav();setMsg('','infoMessage')">
  <h:form id="getfile" enctype="multipart/form-data">
	<div id="contentframe" class="center">
	  <h2>To add items to store(s) for shopping list #{familyBean.shoplist.listname} </h2>
	  <h4>for shopping list under email #{familyBean.email} </h4>
	  <br/>
	  <h4 id="infoMessage" style="infoMessage">#{familyBean.infomsg}#{masterListBean.infomsg}</h4> 

	  <h2 id="subtitle">load file with stores and shopping items </h2>
	  <br/>
	  <h:panelGrid columns="1">
        <h:panelGroup>
				<t:inputFileUpload value="#{loadFilesBean.uploadedFile}" required="true" />
				<h:commandButton value="Upload" actionListener="#{loadFilesBean.uploadFile}" />
        </h:panelGroup>
	  </h:panelGrid>
	</div>
  </h:form>
  <h:form id="getfile2">
	<div id="contentframe" class="center">
	  <h4 align="left">Enter the store's names that you shop from (one per line)</h4>
	  <div><textarea id="storelist" rows = "10" cols = "40"/></div>
		<div id="myModal" class="modal">
		<div class="modal-content">
		  <b>Enter item</b>
		  <table id="storeTbl" border="1">
		  </table>
		  <button type="button" onclick="addShoppingList()" id="modalButton"><b>add items</b></button>
		  <button type="button" onclick="exitTask()" id="modalButton"><b>exit</b></button>
		</div>
	    </div>
      <h:commandButton value="Add Items" onclick="return bldItemTable();" style="margin-right:5px" />
      <h:commandButton value="next" actionListener="#{familyBean.additemList}"  action="addShoppingList.xhtml" style="margin-right:5px" />
	</div>
	<input type="hidden" value="" id="jsonarray" name="jsonarray"/>
  </h:form>
</body>
</html>

src/main/webapp/index.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:h="http://java.sun.com/jsf/html" 
      xmlns:f="http://java.sun.com/jsf/core" 
      xmlns:ui="http://java.sun.com/jsf/facelets" > 
<head>
    <link rel="stylesheet" href="includes/css/scrollNav.css" type="text/css"></link>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script type="text/javascript" src="includes/js/shoplist.js"></script>
    <script type="text/javascript" src="includes/js/shoplistSupport.js"></script>
    <script type="text/javascript" src="includes/js/ajax.js"></script>
</head>  
  <body onload="fadeIn()"> 
	  <ui:include src="mainNavigation.xhtml"/>
	<div id="contentframe" class="content">
	  <ui:include src="selectFamily.xhtml"/>
	</div>
  </body>
</html>

src/main/webapp/selectFamily2.xhtml
<html lang="en"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
<f:view>
	<f:metadata>
        <f:viewParam name="id" value="#{requestBean.tempUser.id}" />
	</f:metadata>

<head>
<f:loadBundle basename="messages" var="bundle" />
<title>#{bundle.addFamily}</title>
    <link rel="stylesheet" href="includes/css/scrollNav.css" type="text/css"></link>
    <link rel="stylesheet" href="includes/css/RepHeader.css" type="text/css"></link>
    <link rel="stylesheet" href="includes/css/style.css" type="text/css"></link>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script type="text/javascript" src="includes/js/shoplist.js"></script>
    <script type="text/javascript" src="includes/js/shoplistSupport.js"></script>
    <script type="text/javascript" src="includes/js/ajax.js"></script>
</head>
<body onload="showNav();setMsg('','infoMessage')">
	<h:form id="addFamily" styleClass="menuCol noborder">
	<div id="contentframe" class="content center">
		<h2>Access to family shopping list</h2>
		
		<h4 id="infoMessage" style="infoMessage">#{familyBean.infomsg} #{masterListBean.infomsg}</h4>
		
	<h:panelGrid columns="4" cellpadding="1" >
		<h:outputLabel for="email" value="Family email" />
		<h:outputText value="*"/>
		<h:inputText id="email" value="#{familyBean.email2}" size="35"  required="#{true}" onchange="setEmailCookie(this);this.form.submit()"/> 
		<h:message for="email" errorClass="error" showSummary="#{true}" showDetail="#{false}" />
		<h:outputLabel for="familyList" value="Shopping list" />
		<h:outputText value=""/>
		<h:selectOneMenu value="#{familyBean.familyId}" id="familyList" immediate="true" onchange="this.form.submit()">
			<f:selectItem itemLabel="Select a family list" itemValue="" />
			<f:selectItems value="#{familyBean.familyList}" /> 
		</h:selectOneMenu>
		<h:message for="familyList" errorClass="error" showSummary="#{true}" showDetail="#{false}" />
	</h:panelGrid>
	<h:panelGrid>
		<h:panelGroup>
          	<h:commandButton value="next" actionListener="#{familyBean.familyViaEmail}"  action="#{familyBean.navigation}" style="margin-right:5px" />
        </h:panelGroup>
	</h:panelGrid>
		<input type="hidden" value="addFamily" id="formname" name="formname"/>
	</div>
	</h:form>
	<ui:debug rendered="#{initParam['javax.faces.PROJECT_STAGE'] eq 'Development'}" hotkey="D" />
</body>
</f:view>
</html>